version: '2'

networks:
  byfn:
    external:
      name: first-network
services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.4.2
        command: launch manager
        environment:
        - CALIPER_BIND_SUT=fabric:2.1.0
        - CALIPER_BENCHCONFIG=caliper/fabcar/config.yaml
        - CALIPER_NETWORKCONFIG=caliper/Network_config.yaml
        - CALIPER_FABRIC_GATEWAY_ENABLED=true
        - CALIPER_FLOW_ONLY_TEST=true
        volumes:
        - ../:/hyperledger/caliper/workspace

